<center> <h2> DS 3000 - Fall 2021</h2> </center>
<center> <h3> DS Report </h3> </center>

<center> <h3>Predicting Start Up Success</h3> </center>
<center><h4>Shaun Khundker, Terry Chen, Lauren MacIver</h4></center>

<hr style="height:2px; border:none; color:black; background-color:black;">

#### Executive Summary:

Add your summary here (100-150 words)

Provide a brief summary of your project. After reading this executive summary, your readers should have a rough understanding of what you did in this project. You can think of this summary in terms of the four sections of the report and write 1-2 sentences describing each section.

<hr style="height:2px; border:none; color:black; background-color:black;">

## Outline
1. <a href='#1'>INTRODUCTION</a>
2. <a href='#2'>METHOD</a>
3. <a href='#3'>RESULTS</a>
4. <a href='#4'>DISCUSSION</a>

<a id="1"></a>
<hr style="height:2px; border:none; color:black; background-color:black;">

## 1. INTRODUCTION

In this section, orient your readers to your project. You've already written some of these in previous deliverables. Based on your final analysis, revise your problem statement and write a concise introduction section. This section should touch upon the following points, but should be written in full paragraphs. Your writing should incorporate all of these points (and more if you like) in a coherent way. Remember that you are trying to convince your readers that this is an important problem to tackle. 

<h4>Problem Statement</h4>

* Describe the problem you would like to tackle. 
* What is the topic of your project? 
* What do you want to learn about it?

<h4>Significance of the Problem</h4>

* Why is it important to tackle this problem in your project?
* In what ways could the insights from this project be useful?
* **(optional)** Has there been previous work on your topic in terms of applying ML techniques to analyze similar datasets? Do some research into your topic. What algorithms were used? What was the performance of those algorithms? Cite your sources appropriately. You can use the numbered reference format or APA (if you are more comfortable with it).

<h4>Questions</h4>

* End this section with a list of data analysis questions you tackled in this project
* You should tie these questions to the problem statement and its significance
    * e.g. Given the aforementioned problem and its importance, we set out to tackle the following questions:
    
    * **Requirement:**
        * You should have at least one question tapping into the comparison of various machine learning algorithms (at least three) in predicting/classifying your target variable from your features variables.



While this section provides bullet points as prompts, your Introduction should consist of coherent paragraphs. You are required delete all the prompts from this template, except for headings. Failing to do so will result in substantial point deductions.

<a id="2"></a>
<hr style="height:2px; border:none; color:black; background-color:black;">

## 2. METHOD

### 2.1. Data Acquisition

* Describe where you obtained your data. Provide a link to the original source. 
* If you scraped your data, include your code as a **separate** Notebook file.
* Your data should be stored in an online repository (e.g., GitHub) and your code should retrieve your data from that online resource. You can read csv files from the Web in the same way that you read files from local drive.
* Describe the dataset (i.e., what it is about) and the number of variables/samples included.

We obtained our data from Kaggle... TODO

### 2.2. Data Analysis
* Describe your predictive model in greater detail. What outcome variable are you going to predict from what feature variables? Why do you think those are important predictors?
* Describe why this is a supervised ML problem and identify the sub-category of the learning task (e.g. classification).
* What machine learning algorithms are you going to use? **Why?** You should list at least three algorithms. Provide a brief description of each algorithm and explain why you think they are appropriate for your data.

Predictive model TODO

<a id="3"></a>
<hr style="height:2px; border:none; color:black; background-color:black;">

## 3. RESULTS

### 3.1. Data Wrangling
In this section, you should do the following and explain why you are doing what you are doing. For each, you should include your code in a cell, followed by a sample output. For instance, if you are one-hot encoding one of your variables, you should first describe what it is and why you are doing it. You should then include your code in a cell, and the sample output should be available as well.

Do at least three of the following:
* Perform simple data cleaning (delete extra columns, deal with NA values, etc.)
* Perform data wrangling to get your features and target values (e.g., grouping your dataframe by columns, applying functions to format dataframes, etc.)
* Preprocess your variables (e.g., scaling/transforming feature variables to normalize them)
* Perform feature extraction (dummy variables, new features from existing features, etc.)

In [72]:
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/shaunkh/DSFinalProject/main/investments_VC.csv", encoding= 'unicode_escape')
df

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,"40,000",operating,EST,NaN,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,"15,00,000",operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
# clean data, drop NA values for our target variable
df = df.dropna(subset=['status'], axis = 0)

# Drop unecessary columns
df = df.drop(['permalink', 'homepage_url', 'category_list', 'founded_month', 'founded_quarter','founded_year'], axis = 1)

# Limit data to only USA
df = df[df["country_code"] == "USA"]

df = df[df["status"] != "operating"]

# Rename columns for ease of use
df = df.rename({' market ': 'market', ' funding_total_usd ': 'funding_total_usd'}, axis=1)

def formatFunding(x):
    val = x.strip()
    val = val.replace(",", "")
    return val

# Format to numbers
df["funding_total_usd"] = df["funding_total_usd"].apply(lambda x: formatFunding(x))
df = df[df["funding_total_usd"] != "-"]
df = df.astype({'funding_total_usd': 'int64'})

#
df = df.drop(["country_code", "region", "city"], axis=1)
df = df.dropna(subset=['state_code'], axis = 0)
df = df.dropna(subset=['market'], axis = 0)

df = df.astype({'market': 'str', 'name': 'str', 'status': 'str', 'state_code': 'str'})

df[["market", "name", "status", "state_code"]] = df[["market", "name", "status", "state_code"]].apply(lambda x: x.str.strip())
df

,name,market,funding_total_usd,status,state_code,funding_rounds,founded_at,first_funding_at,last_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,1750000,acquired,NY,1.0,2012-06-01,2012-06-30,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,1000memories,Curated Web,2535000,acquired,CA,2.0,2010-07-01,2010-01-01,2011-02-16,15000.0,...,0.0,0.0,2520000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,100Plus,Analytics,1250000,acquired,CA,2.0,2011-09-16,2011-11-02,2011-11-30,750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,10BestThings,Curated Web,50000,closed,OH,1.0,2009-04-01,2009-04-01,2009-04-01,50000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,170 Systems,Software,14000000,acquired,MA,1.0,1990-01-01,2002-04-16,2002-04-16,0.0,...,0.0,0.0,14000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49372,Zume Life,iPhone,1700000,closed,CA,2.0,2006-07-25,2007-01-01,2008-04-01,700000.0,...,0.0,0.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49394,Zuujit,E-Commerce,2700000,closed,CA,1.0,2010-01-01,2010-04-30,2010-04-30,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49400,Zvents,Entertainment,55200000,acquired,CA,4.0,2005-03-01,2005-10-05,2011-09-30,200000.0,...,0.0,0.0,7000000.0,24000000.0,24000000.0,0.0,0.0,0.0,0.0,0.0
49414,Zykis,Automotive,800000,closed,CA,1.0,2006-10-27,2006-10-27,2006-10-27,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49419,Zymetis,Biotechnology,2257464,closed,MD,2.0,2006-01-01,2010-01-11,2010-01-31,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [74]:
features = df.iloc[:, 1:5]
features = features.drop(["funding_total_usd", "status"], axis=1)

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse = False)

encoded_df = encoder.fit_transform(features)

feature_names = encoder.get_feature_names(["market", "state_code"])

features_df = pd.DataFrame(encoded_df, columns = feature_names)
features_df

,market_Accounting,market_Advertising,market_Advertising Platforms,market_Advice,market_Aerospace,market_Agriculture,market_All Markets,market_All Students,market_Analytics,market_Android,...,state_code_RI,state_code_SC,state_code_TN,state_code_TX,state_code_UT,state_code_VA,state_code_VT,state_code_WA,state_code_WI,state_code_WV
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3682,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3683,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3684,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3685,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3686,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [80]:
df_new = df.drop(["market", "state_code"], axis = 1)
frames = [df, df_new]
df_new = pd.concat(frames, axis = 1)
df_new

,name,market,funding_total_usd,status,state_code,funding_rounds,founded_at,first_funding_at,last_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,1750000,acquired,NY,1.0,2012-06-01,2012-06-30,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,1000memories,Curated Web,2535000,acquired,CA,2.0,2010-07-01,2010-01-01,2011-02-16,15000.0,...,0.0,0.0,2520000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,100Plus,Analytics,1250000,acquired,CA,2.0,2011-09-16,2011-11-02,2011-11-30,750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,10BestThings,Curated Web,50000,closed,OH,1.0,2009-04-01,2009-04-01,2009-04-01,50000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,170 Systems,Software,14000000,acquired,MA,1.0,1990-01-01,2002-04-16,2002-04-16,0.0,...,0.0,0.0,14000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49372,Zume Life,iPhone,1700000,closed,CA,2.0,2006-07-25,2007-01-01,2008-04-01,700000.0,...,0.0,0.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49394,Zuujit,E-Commerce,2700000,closed,CA,1.0,2010-01-01,2010-04-30,2010-04-30,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49400,Zvents,Entertainment,55200000,acquired,CA,4.0,2005-03-01,2005-10-05,2011-09-30,200000.0,...,0.0,0.0,7000000.0,24000000.0,24000000.0,0.0,0.0,0.0,0.0,0.0
49414,Zykis,Automotive,800000,closed,CA,1.0,2006-10-27,2006-10-27,2006-10-27,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49419,Zymetis,Biotechnology,2257464,closed,MD,2.0,2006-01-01,2010-01-11,2010-01-31,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 3.2. Data Exploration
* Generate appropriate data visualizations for your key variables identified in the previous section
* You should have at least three visualizations (and at least two different visualization types)
* For each visualization provide an explanation regarding the variables involved and an interpretation of the graph. In other words, what does the graph represent?
* Insert your visualizations as images as well (upload the graph images to an online source, e.g. github or imgbb, and embed those into the cells in Jupyter Notebook, similar to HWs). This is a requirement.

### 3.3. Model Training
* For your machine learning question(s), use the Training, Validation, and Testing approach through GridSearch
* Apply machine learning algorithms (apply at least three different algorithms)
* Train your algorithms using your **training set**

* Evaluate the performance of your algorithms using appropriate evaluation metrics
    * Use at least two different metrics
    * Remember GridSearch will use cross-validation

* Is there any indication of overfitting/underfitting?

* Use one feature selection technique to select a subset of your original features and train your models with the selected features as well (the idea is to see if you can achieve the same using a fewer number of features)

    * **Hint:** You can run your model with all your features and with your selected features, comparing the results (similar to the corresponding HW assignment).

### 3.4. Model Optimization
* Tune your models using hyperparameters appropriate for your algorithms
* Explain why you are doing this (e.g., to avoid overfitting, etc.)

### 3.5. Model Testing
* Test your tuned algorithms using your **testing set**

<a id="4"></a>
<hr style="height:2px; border:none; color:black; background-color:black;">

## 4. DISCUSSION
* Interpret your findings from 3.3, 3.4, and 3.5
    * Which algorithms did you compare?
    * Which algorithm(s) revealed best performance? With what parameters?
    * Which algorithm(s) should be used for your predictive model?
    * Based on your findings, can we use the features in your dataset to predict the outcome variable you identified using the algorithms you've applied? (It is okay if the answer is no. We're interested in the process, not the performance of the model.)

* Discuss the ethical implications of your project. Should your results be accepted at face value, why or why not? (e.g. any dataset bias or methodological issues?)

* End this section with a conclusion paragraph containing some pointers for future work
    * (e.g., get more data/features, perform another analysis, etc.)

<a id="5"></a>
<hr style="height:2px; border:none; color:black; background-color:black;">

### CONTRIBUTIONS
* Describe each team member's contributions to the report (who did what in each section)
* Remember this is a team effort!
* Each member of your team will later provide peer evaluation of other team members. Your final grade on the project will be based on those peer evaluations. A survey will be shared after the deadline for this deliverable.