In [150]:
import pandas as pd
import numpy as np

In [178]:
d = pd.read_csv("investments_VC.csv", encoding= 'unicode_escape')
d

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,"40,000",operating,EST,NaN,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,"15,00,000",operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [179]:
d = d.dropna(subset=['status'], axis = 0)
d

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,"40,000",operating,EST,NaN,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,"15,00,000",operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49433,/organization/zzish,Zzish,http://www.zzish.com,|Analytics|Gamification|Developer APIs|iOS|And...,Education,"3,20,000",operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49434,/organization/zznode-science-and-technology-co...,ZZNode Science and Technology,http://www.zznode.com,|Enterprise Software|,Enterprise Software,"15,87,301",operating,CHN,NaN,Beijing,...,0.0,0.0,1587301.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49435,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,|Web Development|Advertising|Wireless|Mobile|,Web Development,"97,398",operating,HRV,NaN,Split,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49436,/organization/a-list-games,[a]list games,http://www.alistgames.com,|Games|,Games,"93,00,000",operating,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49437,/organization/x,[x+1],http://www.xplusone.com/,|Enterprise Software|,Enterprise Software,"4,50,00,000",operating,USA,NY,New York City,...,0.0,0.0,16000000.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [180]:
d.columns

Index(['permalink', 'name', 'homepage_url', 'category_list', ' market ',
       ' funding_total_usd ', 'status', 'country_code', 'state_code', 'region',
       'city', 'funding_rounds', 'founded_at', 'founded_month',
       'founded_quarter', 'founded_year', 'first_funding_at',
       'last_funding_at', 'seed', 'venture', 'equity_crowdfunding',
       'undisclosed', 'convertible_note', 'debt_financing', 'angel', 'grant',
       'private_equity', 'post_ipo_equity', 'post_ipo_debt',
       'secondary_market', 'product_crowdfunding', 'round_A', 'round_B',
       'round_C', 'round_D', 'round_E', 'round_F', 'round_G', 'round_H'],
      dtype='object')

In [181]:
d = d.drop(['permalink', 'homepage_url', 'category_list', 'founded_month','founded_quarter','founded_year'], axis = 1)
d

,name,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,"17,50,000",acquired,USA,NY,New York City,New York,1.0,2012-06-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,&TV Communications,Games,"40,00,000",operating,USA,CA,Los Angeles,Los Angeles,2.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,'Rock' Your Paper,Publishing,"40,000",operating,EST,NaN,Tallinn,Tallinn,1.0,2012-10-26,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,(In)Touch Network,Electronics,"15,00,000",operating,GBR,NaN,London,London,1.0,2011-04-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-R- Ranch and Mine,Tourism,"60,000",operating,USA,TX,Dallas,Fort Worth,2.0,2014-01-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49433,Zzish,Education,"3,20,000",operating,GBR,NaN,London,London,1.0,2013-01-28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49434,ZZNode Science and Technology,Enterprise Software,"15,87,301",operating,CHN,NaN,Beijing,Beijing,1.0,NaN,...,0.0,0.0,1587301.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49435,Zzzzapp Wireless ltd.,Web Development,"97,398",operating,HRV,NaN,Split,Split,5.0,2012-05-13,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49436,[a]list games,Games,"93,00,000",operating,NaN,NaN,NaN,NaN,1.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49437,[x+1],Enterprise Software,"4,50,00,000",operating,USA,NY,New York City,New York,4.0,1999-01-01,...,0.0,0.0,16000000.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [182]:
d.columns

Index(['name', ' market ', ' funding_total_usd ', 'status', 'country_code',
       'state_code', 'region', 'city', 'funding_rounds', 'founded_at',
       'first_funding_at', 'last_funding_at', 'seed', 'venture',
       'equity_crowdfunding', 'undisclosed', 'convertible_note',
       'debt_financing', 'angel', 'grant', 'private_equity', 'post_ipo_equity',
       'post_ipo_debt', 'secondary_market', 'product_crowdfunding', 'round_A',
       'round_B', 'round_C', 'round_D', 'round_E', 'round_F', 'round_G',
       'round_H'],
      dtype='object')

In [183]:
d = d[d["country_code"] == "USA"]

In [184]:
d

,name,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,"17,50,000",acquired,USA,NY,New York City,New York,1.0,2012-06-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,&TV Communications,Games,"40,00,000",operating,USA,CA,Los Angeles,Los Angeles,2.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-R- Ranch and Mine,Tourism,"60,000",operating,USA,TX,Dallas,Fort Worth,2.0,2014-01-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,004 Technologies,Software,-,operating,USA,IL,"Springfield, Illinois",Champaign,1.0,2010-01-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,1-4 All,Software,-,operating,USA,NC,NC - Other,Connellys Springs,1.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49426,Zynga,Technology,"86,65,50,786",operating,USA,CA,SF Bay Area,San Francisco,9.0,2007-07-01,...,0.0,0.0,15026000.0,355187000.0,490000000.0,0.0,0.0,0.0,0.0,0.0
49427,Zyngenia,Biotechnology,"2,50,00,000",operating,USA,MD,"Washington, D.C.",Gaithersburg,1.0,2008-01-01,...,0.0,0.0,25000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49429,ZYOMYX,Biotechnology,"3,42,75,015",operating,USA,MO,MO - Other,Fremont,4.0,1998-01-01,...,0.0,0.0,0.0,12000000.0,0.0,0.0,0.0,0.0,0.0,0.0
49431,Zyrra,E-Commerce,"15,10,500",operating,USA,MA,Boston,Cambridge,4.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49437,[x+1],Enterprise Software,"4,50,00,000",operating,USA,NY,New York City,New York,4.0,1999-01-01,...,0.0,0.0,16000000.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [185]:
d = d[d["status"] != "operating"]
d

,name,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,"17,50,000",acquired,USA,NY,New York City,New York,1.0,2012-06-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,1000memories,Curated Web,"25,35,000",acquired,USA,CA,SF Bay Area,San Francisco,2.0,2010-07-01,...,0.0,0.0,2520000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,100Plus,Analytics,"12,50,000",acquired,USA,CA,SF Bay Area,San Francisco,2.0,2011-09-16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,10BestThings,Curated Web,"50,000",closed,USA,OH,Cleveland,Cleveland,1.0,2009-04-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,12Society,E-Commerce,-,acquired,USA,CA,Los Angeles,West Hollywood,1.0,2012-01-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49394,Zuujit,E-Commerce,"27,00,000",closed,USA,CA,Santa Barbara,Santa Barbara,1.0,2010-01-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49395,zuuka!,Apps,-,acquired,USA,CA,Santa Barbara,Santa Barbara,2.0,2009-04-10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49400,Zvents,Entertainment,"5,52,00,000",acquired,USA,CA,SF Bay Area,San Mateo,4.0,2005-03-01,...,0.0,0.0,7000000.0,24000000.0,24000000.0,0.0,0.0,0.0,0.0,0.0
49414,Zykis,Automotive,"8,00,000",closed,USA,CA,Anaheim,Irvine,1.0,2006-10-27,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49419,Zymetis,Biotechnology,"22,57,464",closed,USA,MD,"Washington, D.C.",College Park,2.0,2006-01-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [186]:
# d.to_csv("investments_VC_cleaned", encoding='utf-8', index=False)

In [187]:
d = d.rename({' market ': 'market', ' funding_total_usd ': 'funding_total_usd'}, axis=1)

In [188]:
def formatFunding(x):
    val = x.strip()
    val = val.replace(",", "")
    return val

In [189]:
d["funding_total_usd"] = d["funding_total_usd"].apply(lambda x: formatFunding(x))
d

,name,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,1750000,acquired,USA,NY,New York City,New York,1.0,2012-06-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,1000memories,Curated Web,2535000,acquired,USA,CA,SF Bay Area,San Francisco,2.0,2010-07-01,...,0.0,0.0,2520000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,100Plus,Analytics,1250000,acquired,USA,CA,SF Bay Area,San Francisco,2.0,2011-09-16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,10BestThings,Curated Web,50000,closed,USA,OH,Cleveland,Cleveland,1.0,2009-04-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,12Society,E-Commerce,-,acquired,USA,CA,Los Angeles,West Hollywood,1.0,2012-01-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49394,Zuujit,E-Commerce,2700000,closed,USA,CA,Santa Barbara,Santa Barbara,1.0,2010-01-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49395,zuuka!,Apps,-,acquired,USA,CA,Santa Barbara,Santa Barbara,2.0,2009-04-10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49400,Zvents,Entertainment,55200000,acquired,USA,CA,SF Bay Area,San Mateo,4.0,2005-03-01,...,0.0,0.0,7000000.0,24000000.0,24000000.0,0.0,0.0,0.0,0.0,0.0
49414,Zykis,Automotive,800000,closed,USA,CA,Anaheim,Irvine,1.0,2006-10-27,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49419,Zymetis,Biotechnology,2257464,closed,USA,MD,"Washington, D.C.",College Park,2.0,2006-01-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [190]:
d = d[d["funding_total_usd"] != "-"]

In [191]:
d = d.astype({'funding_total_usd': 'int64'})

In [192]:
d = d.drop(["country_code", "region", "city"], axis=1)

In [193]:
d

,name,market,funding_total_usd,status,state_code,funding_rounds,founded_at,first_funding_at,last_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,1750000,acquired,NY,1.0,2012-06-01,2012-06-30,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,1000memories,Curated Web,2535000,acquired,CA,2.0,2010-07-01,2010-01-01,2011-02-16,15000.0,...,0.0,0.0,2520000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,100Plus,Analytics,1250000,acquired,CA,2.0,2011-09-16,2011-11-02,2011-11-30,750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,10BestThings,Curated Web,50000,closed,OH,1.0,2009-04-01,2009-04-01,2009-04-01,50000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,170 Systems,Software,14000000,acquired,MA,1.0,1990-01-01,2002-04-16,2002-04-16,0.0,...,0.0,0.0,14000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49372,Zume Life,iPhone,1700000,closed,CA,2.0,2006-07-25,2007-01-01,2008-04-01,700000.0,...,0.0,0.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49394,Zuujit,E-Commerce,2700000,closed,CA,1.0,2010-01-01,2010-04-30,2010-04-30,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49400,Zvents,Entertainment,55200000,acquired,CA,4.0,2005-03-01,2005-10-05,2011-09-30,200000.0,...,0.0,0.0,7000000.0,24000000.0,24000000.0,0.0,0.0,0.0,0.0,0.0
49414,Zykis,Automotive,800000,closed,CA,1.0,2006-10-27,2006-10-27,2006-10-27,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49419,Zymetis,Biotechnology,2257464,closed,MD,2.0,2006-01-01,2010-01-11,2010-01-31,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [194]:
d.columns

Index(['name', 'market', 'funding_total_usd', 'status', 'state_code',
       'funding_rounds', 'founded_at', 'first_funding_at', 'last_funding_at',
       'seed', 'venture', 'equity_crowdfunding', 'undisclosed',
       'convertible_note', 'debt_financing', 'angel', 'grant',
       'private_equity', 'post_ipo_equity', 'post_ipo_debt',
       'secondary_market', 'product_crowdfunding', 'round_A', 'round_B',
       'round_C', 'round_D', 'round_E', 'round_F', 'round_G', 'round_H'],
      dtype='object')

In [195]:
d = d.astype({'market': 'str', 'name': 'str', 'status': 'str', 'state_code': 'str'})

In [196]:
d

,name,market,funding_total_usd,status,state_code,funding_rounds,founded_at,first_funding_at,last_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,1750000,acquired,NY,1.0,2012-06-01,2012-06-30,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,1000memories,Curated Web,2535000,acquired,CA,2.0,2010-07-01,2010-01-01,2011-02-16,15000.0,...,0.0,0.0,2520000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,100Plus,Analytics,1250000,acquired,CA,2.0,2011-09-16,2011-11-02,2011-11-30,750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,10BestThings,Curated Web,50000,closed,OH,1.0,2009-04-01,2009-04-01,2009-04-01,50000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,170 Systems,Software,14000000,acquired,MA,1.0,1990-01-01,2002-04-16,2002-04-16,0.0,...,0.0,0.0,14000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49372,Zume Life,iPhone,1700000,closed,CA,2.0,2006-07-25,2007-01-01,2008-04-01,700000.0,...,0.0,0.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49394,Zuujit,E-Commerce,2700000,closed,CA,1.0,2010-01-01,2010-04-30,2010-04-30,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49400,Zvents,Entertainment,55200000,acquired,CA,4.0,2005-03-01,2005-10-05,2011-09-30,200000.0,...,0.0,0.0,7000000.0,24000000.0,24000000.0,0.0,0.0,0.0,0.0,0.0
49414,Zykis,Automotive,800000,closed,CA,1.0,2006-10-27,2006-10-27,2006-10-27,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49419,Zymetis,Biotechnology,2257464,closed,MD,2.0,2006-01-01,2010-01-11,2010-01-31,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [198]:
d[["market", "name", "status", "state_code"]] = d[["market", "name", "status", "state_code"]].apply(lambda x: x.str.strip())

In [199]:
d

,name,market,funding_total_usd,status,state_code,funding_rounds,founded_at,first_funding_at,last_funding_at,seed,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,#waywire,News,1750000,acquired,NY,1.0,2012-06-01,2012-06-30,2012-06-30,1750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,1000memories,Curated Web,2535000,acquired,CA,2.0,2010-07-01,2010-01-01,2011-02-16,15000.0,...,0.0,0.0,2520000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,100Plus,Analytics,1250000,acquired,CA,2.0,2011-09-16,2011-11-02,2011-11-30,750000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,10BestThings,Curated Web,50000,closed,OH,1.0,2009-04-01,2009-04-01,2009-04-01,50000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,170 Systems,Software,14000000,acquired,MA,1.0,1990-01-01,2002-04-16,2002-04-16,0.0,...,0.0,0.0,14000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49372,Zume Life,iPhone,1700000,closed,CA,2.0,2006-07-25,2007-01-01,2008-04-01,700000.0,...,0.0,0.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49394,Zuujit,E-Commerce,2700000,closed,CA,1.0,2010-01-01,2010-04-30,2010-04-30,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49400,Zvents,Entertainment,55200000,acquired,CA,4.0,2005-03-01,2005-10-05,2011-09-30,200000.0,...,0.0,0.0,7000000.0,24000000.0,24000000.0,0.0,0.0,0.0,0.0,0.0
49414,Zykis,Automotive,800000,closed,CA,1.0,2006-10-27,2006-10-27,2006-10-27,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49419,Zymetis,Biotechnology,2257464,closed,MD,2.0,2006-01-01,2010-01-11,2010-01-31,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [202]:
d["market"].unique()

array(['News', 'Curated Web', 'Analytics', 'Software', 'E-Commerce',
       'Finance', 'Electronic Health Records', 'Games', 'Web Hosting',
       'Clean Technology', 'Security', 'Cloud Computing', 'Video',
       'Internet Marketing', 'Virtual Worlds', 'Telecommunications',
       'Biotechnology', 'Search', 'Health Care', 'Career Management',
       'Services', 'Consulting', 'Enterprise Software', 'Android',
       'Mobile', 'nan', 'Social Media Advertising', 'Television',
       'Advertising', 'Public Relations', 'Publishing', 'Entertainment',
       'Sales and Marketing', 'Health and Wellness',
       'Local Based Services', 'Auctions', 'Displays', 'Messaging',
       'Social Commerce', 'Clean Energy', 'Hardware + Software', 'SaaS',
       'Semiconductors', 'Wireless', 'Social Media', 'Nanotechnology',
       'Transportation', 'iPhone', 'Personal Branding', 'Lighting',
       'Credit', 'Data Mining', 'Agriculture', 'Manufacturing',
       'Education', 'Reviews and Recommendations', 'Medical', 'Internet',
       'Opinions', 'Information Technology', 'Homeland Security',
       'Restaurants', 'Testing', 'Automotive', 'Mobile Commerce',
       'Web Tools', 'Diagnostics', 'Real Time', 'Productivity Software',
       'Artificial Intelligence', 'SEO', 'Nonprofits', 'Legal',
       'Monetization', 'Business Development', 'Music', 'Solar',
       'Creative Industries', 'Video Streaming', 'Networking', 'Media',
       'Contact Management', 'Peer-to-Peer', 'Fitness', 'Hardware',
       'Social Network Media', 'Wine And Spirits', 'Sports', 'Startups',
       'Coupons', 'Payments', 'Cloud Data Services', 'Mobility',
       'Semiconductor Manufacturing Equipment', 'Robotics', 'Storage',
       'Infrastructure', 'Location Based Services', 'Blogging Platforms',
       'Flash Sales', 'Lifestyle', 'Databases', 'Video Games',
       'Hospitality', 'World Domination', 'Accounting', 'Mobile Games',
       'Web Development', 'Parenting', 'File Sharing', 'Navigation',
       'Marketplaces', 'Group Buying', 'Mobile Payments',
       'Pharmaceuticals', 'Big Data', 'Medical Devices', 'Auto', 'Cars',
       'Real Estate', 'Predictive Analytics', 'Facebook Applications',
       'Outsourcing', 'Flash Storage', 'MMO Games', 'Hospitals',
       'Technology', 'Local', 'Classifieds', 'Environmental Innovation',
       'Ediscovery', 'Search Marketing', 'Photography',
       'Cloud Management', 'Tablets', 'PaaS', 'Collaboration', 'Leisure',
       'Proximity Internet', 'Beauty', 'Art', 'Web CMS',
       'Personalization', 'Travel', 'Private Social Networking', 'Chat',
       'Internet of Things', 'Optimization', 'Photo Sharing',
       'Local Businesses', 'Twitter Applications', 'Content', 'Events',
       'Open Source', 'Shopping', 'Online Scheduling', 'Design',
       'Consumer Internet', 'Tech Field Support', 'Consumer Electronics',
       'Lead Generation', 'Life Sciences', 'Social Games', 'Maps',
       'Distribution', 'Online Shopping', 'Fashion', 'Shipping',
       'Indoor Positioning', 'Customer Support Tools',
       'Communications Infrastructure', 'Digital Media', 'Consumer Goods',
       'Gambling', 'Electronics', 'Trading', 'Fantasy Sports',
       'Video on Demand', 'iPad', 'Credit Cards',
       'Social Media Marketing', 'Public Transportation', 'Enterprises',
       'Bioinformatics', 'Finance Technology', 'High Schools',
       'Data Security', 'Customer Service', 'Politics',
       'Marketing Automation', 'Commodities', 'Venture Capital',
       'Data Integration', 'Brand Marketing', 'Pets', 'Developer Tools',
       'Renewable Energies', 'Recycling', 'Browser Extensions', 'Guides',
       'Organic Food', 'Linux', 'Gift Card', 'Surveys',
       'Business Intelligence', 'Tutoring', 'VoIP', 'Taxis', 'Consumers',
       'Email Marketing', 'Big Data Analytics', 'Clinical Trials',
       'Online Rental', 'Home & Garden', 'Video Chat', 'Apps', 'Email',
       'Recruiting', 'Travel & Tourism', 'Business Services',
       'IT and Cybersecurity', 'Privacy', 'Energy Efficiency',
       'Market Research', 'CRM', 'All Markets', 'Product Design',
       'Virtual Goods', 'Audio', 'Employment', 'Kids', 'Web Browsers',
       'Archiving', 'SMS', 'Unifed Communications', 'Licensing',
       'Digital Rights Management', 'Information Services',
       'Demographies', 'Film', 'Task Management', 'DIY', 'Diabetes',
       'Internet TV', 'Neuroscience', 'Gps', 'Virtual Currency', 'Game',
       'Cable', 'Cloud Security', 'Mobile Advertising', 'Shoes',
       'Celebrity', 'Colleges', 'Incentives', 'Banking',
       'Medical Professionals', 'Retail', 'Home Automation',
       'Mobile Software Tools', 'Career Planning', 'Humanitarian', 'IaaS',
       'Oil', 'Healthcare Services', 'Document Management',
       'Interest Graph', 'Game Mechanics', 'Photo Editing',
       'Local Search', 'Communities', 'Social Media Monitoring',
       'Web Design', 'Physicians', 'Financial Services', 'Social Search',
       'Journalism', 'Risk Management', 'All Students', 'Crowdsourcing',
       'Price Comparison', 'Energy', 'Advertising Platforms',
       'Subscription Businesses', 'Network Security', 'Machine Learning',
       'Tracking', 'Reputation', 'M2M', 'Professional Networking',
       'Semantic Web', 'Social Bookmarking', 'Training', 'B2B',
       'Concerts', 'Visual Search', 'Vacation Rentals', 'Windows Phone 7',
       'Translation', 'Entrepreneur', 'MicroBlogging', 'Hotels',
       'Collaborative Consumption', 'Fraud Detection', 'Lead Management',
       'Computers', 'Service Providers', 'Aerospace', 'iPod Touch',
       'Human Resources', 'Graphics', 'Social Buying', 'Contests',
       'Data Centers', 'Virtualization', 'Mac', 'Sustainability',
       'Crowdfunding', 'Babies', 'Online Reservations', 'DOD/Military',
       'Forums', 'Meeting Software', 'Content Discovery', 'RFID',
       'Advice', 'Ticketing', 'Stock Exchanges', 'Charity', 'Toys',
       'Supply Chain Management', 'Information Security',
       'Energy Management', 'Visualization', 'Promotional',
       'Developer APIs', 'Communications Hardware', 'Law Enforcement',
       'Discounts', 'Social Travel', 'E-Commerce Platforms',
       'Trusted Networks', 'Billing', 'Architecture',
       'Speech Recognition', 'Mobile Devices', 'Social Recruiting',
       'Postal and Courier Services', 'Cooking'], dtype=object)

In [200]:
# d.to_csv("investments_VC_cleaned.csv", encoding='utf-8', index=False)